### PR TITLE
Update test to use v2 endpoint of build service

### PR DESCRIPTION
**Pull request by onishiweb**

### CODE REVIEW

**Comment by AlbertoElias** [comment]
CI is failing, it's using the old obt, travis should be downloading the _node4_ branch of obt

**Comment by onishiweb** [comment]
@AlbertoElias is there a way to fix that? Is it a travis config issue or something I can fix in the code?

**Comment by AlbertoElias** [comment]
It's a travis config issue. The most up to date travis config file is hosted here: http://origami.ft.com/docs/component-spec/modules/#continuous-integration

**Comment by onishiweb** [comment]
Ok cool, updated now. Fingers crossed that's everything fixed now.

**Comment by onishiweb** [comment]
Have a bit of an unknown going on, I get parse errors whenever I use `let` instead of `var` in `obt test`. But I get errors in ESLint saying I should use let or const. Help?

**Comment by AlbertoElias** [comment]
What version of obt/node are you using?

**Comment by onishiweb** [comment]
Node `4.3.1` Obt `v5.0.0` but I think it's still my local version with the fix when there's only JS or Sass to test.

**Comment by AlbertoElias** [comment]
If you could test it out with the latest stable obt in master, that'd be great

**Comment by onishiweb** [comment]
All tests have now been fixed in #103

**Pull request closed without merging**
