### PR TITLE
increase overlay z-index to be greater than the ft.com sticky header

### PR DESCRIPTION
**Pull request by pixelandpage**
So I think that this is all that's required to increase the z-index of o-overlays. It's almost worryingly simple so if you think I've missed something, please shout 😄 

In any case, I was thinking that this should be a minor release as it changes the way the element displays - guidance on minor v patch welcome 🙇

### CODE REVIEW

**Comment by pixelandpage** [comment]
Failing build is failing 🚧 🔨

**Comment by alicebartlett** [comment]
The o-overlay tests sometimes ✨randomly fail✨ so I rebuilt them and this time they work

**Comment by notlee** [comment]
Hey @pixelandpage. Overlays are sometimes used nested within content. 
https://www.ft.com/__origami/service/build/v2/demos/o-overlay@2.1.0/sliding-notification?lm
In a case such as that the overlay having a higher z-index than the sticky header would look weird.

Instead we could increase the z-index on `.o-overlay--full-height.o-overlay--full-width`, so the overlay is only above the sticky header when it's full height and width. Does that cover your use case?

**Comment by pixelandpage** [comment]
@notlee Sounds very sensible; in this use case (clicking a myFT save article button) it looks like we're applying `--full-width`, but not `--full-height` (strange). So could we apply this change if either class is being used rather than both?

**Comment by pixelandpage** [comment]
Closing this after deciding on a different solution with @notlee

**Pull request closed without merging**
