### PR TITLE
Fix the icon cross hover state and shaded states

### PR DESCRIPTION
**Pull request by onishiweb**
Fully closes #110

### CODE REVIEW

**Comment by onishiweb** [comment]
@wheresrhys This fixes the issue with no close icon appearing in the shaded header, and the hover states on regular overlays.

**Comment by wheresrhys** [comment]
thanks for fixing so quickly.

**Comment by AlbertoElias** [comment]
+1

**Comment by onishiweb** [comment]
Happy for me to merge @AlbertoElias ?

**Comment by AlbertoElias** [comment]
Yes!

On Wed, 25 May 2016 at 10:48 Adam Onishi <notifications@github.com> wrote:

> Happy for me to merge @AlbertoElias <https://github.com/AlbertoElias> ?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-overlay/pull/111#issuecomment-221525411>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request merged**
