### PR TITLE
Bump ftdomdelegates

### PR DESCRIPTION
**Pull request by liamkeaton**

### CODE REVIEW

**Comment by i-like-robots** [comment]
I did not anticipate this issue when re-naming the module but I suppose it is something we need to push through. Part of the work done to publish Origami components to npm was to add mappings for packages with different names, one of those is `ftdomdeletegate` => `dom-delegate`.

https://github.com/Financial-Times/origami-component-converter/blob/4380b360f871728dc8ce04f6eee587ff8e61be76/config/mappings.js

**Comment by notlee** [comment]
Thanks 👍 As it's a breaking change I'm going to open a PR which tidies up a couple of other breaking issues at the same time. I'll upgrade other components too, which include:

- o-tracking
- o-ads
- o-overlay
- o-share
- o-gallery
- o-table
- o-tooltip
- o-audio
- o-comments

**Comment by notlee** [comment]
https://github.com/Financial-Times/o-overlay/pull/187

**Comment by notlee** [comment]
I'm going to close this in favor of https://github.com/Financial-Times/o-overlay/pull/187
Soon as I get access to the `the-ft` npm user, I'll be able to publish origami-component-converter and get the builds passing.

**Pull request closed without merging**
